version: '3'

services:
  # COMPASS CONNECTION STRINGS
  # auth + 2-node    : mongodb://admin:admin@my_mongodb_1:27017,my_mongodb_2:27018/?replicaSet=rs0
  # no auth + 1-node : mongodb://my_mongodb_1:27017,my_mongodb_2:27018/?replicaSet=rs0
  # no-auth + 1-node : mongodb://my_mongodb_1:27017/?replicaSet=rs0
  # auth + 1-node    : mongodb://admin:admin@my_mongodb_1:27017/?replicaSet=rs0

  # SHELL COMMANDS
  # - with auth : mongo --port 27017 -u "admin" -p "admin" --authenticationDatabase "admin"
  # - without auth : mongo

  # MONGO SHELL COMMANDS
  # rs.slaveOk()  -> start making quey
  # rs.initiate() -> init rs
  # use local     -> "oplog.rs" collection is inside "local" DB
  # db.oplog.rs.find()  -> query "oplog.rs"

  # random
  # db.addUser({
  #     user: 'my_oplog_user',
  #     pwd: 'my_oplog_pass',
  #     roles: [{"role": "readAnyDatabase", "db": "local"}]
  # })



  my_mongodb_1:
    image: mongo:8.0.0
    hostname: my_mongodb_1
    container_name: my_mongodb_1
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #    chmod 400 /etc/mongodb.key
    #    chown 999:999 /etc/mongodb.key
    #    mongod --replSet rs0 --keyFile /etc/mongodb.key --bind_ip_all
    # command: ["mongod", "--config", "/etc/mongod.conf"]
    # command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongodb.key", "--config" ,"/etc/mongod.conf"]
    # command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    command: [mongod, --replSet, rs0, --keyFile, /etc/mongodb.key, --bind_ip_all, --port, "27017"]
    # healthcheck:
    #   test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({})} catch(e) {rs.status().ok}") -eq 1
    #   interval: 10s
    #   start_period: 30s
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # - ./volume/mongo/internal/db:/data/db
      # - ./volume/mongo/internal/configdb:/data/configdb
      - ./volume/mongo/external/mongod.conf:/etc/mongod.conf
      - ./volume/mongo/external/mongodb.key:/etc/mongodb.key


  mongodb_setup:
    image: mongo:8.0.0
    container_name: mongodb_setup
    hostname: mongodb_setup
    restart: 'no'
    command: >
      mongosh mongodb://admin:admin@my_mongodb_1:27017/?replicaSet=rs0&directConnection=true
      '
      rs.slaveOk();
      rs.initiate();
      '
    depends_on:
      - my_mongodb_1