version: '3'

services:

  my_zk:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: my_zk
    container_name: my_zk
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: my_zk:2888:3888

  my_kafka_1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: my_kafka_1
    container_name: my_kafka_1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://my_kafka_1:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "my_zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      TOPIC_AUTO_CREATE : "true"
    depends_on:
      - my_zk

  my_dbzm:
    image: 'debezium/connect:2.1.2.Final'
    hostname: my_dbzm
    container_name: my_dbzm
    ports:
      - 9095:8083
    environment:
     - BOOTSTRAP_SERVERS=my_kafka_1:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=connect_configs
     - OFFSET_STORAGE_TOPIC=connect_offsets
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://my_schema_registry:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://my_schema_registry:8081
     - CONNECT_CONFIG_STORAGE_TOPIC=delete
     - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
     - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
     - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
    depends_on:
      - my_zk
      - my_kafka_1
    volumes:
      - ./volume/dbzm/external:/dbzm_curls

  my_schema_registry:
    image: confluentinc/cp-schema-registry:5.5.3
    hostname: my_schema_registry
    container_name: my_schema_registry
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=my_schema_registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://my_kafka_1:9092
    ports:
      - 8081:8081
    depends_on:
      - my_zk
      - my_kafka_1
      - my_dbzm

  my_mongodb_1:
    image: mongo:8.0.0
    hostname: my_mongodb_1
    container_name: my_mongodb_1
    ports:
      - 27017:27017
    restart: 'no'
    command: mongod --replSet rs0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  # zoo_ui:
  #   image: elkozmon/zoonavigator:latest
  #   container_name: zoo_ui
  #   hostname: zoo_ui
  #   restart: 'no'
  #   ports:
  #     - 9000:9000
  #   environment:
  #     HTTP_PORT: 9000
  #   depends_on:
  #     - my_zk
  #     - my_kafka_1

  # kafka_ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka_ui
  #   hostname: kafka_ui
  #   restart: 'no'
  #   ports:
  #     - 9100:8080
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   depends_on:
  #     - my_zk
  #     - my_kafka_1

  # dbzm_ui:
  #   image: debezium/debezium-ui:latest
  #   container_name: dbzm_ui
  #   hostname: dbzm_ui
  #   restart: 'no'
  #   depends_on:
  #    - my_dbzm
  #   ports:
  #     - '8844:8080'
  #   environment:
  #     KAFKA_CONNECT_URIS: http://my_dbzm:8083